Repository sous-chefs/rsyslog, pull requests merged in 2020-11, with the labels that each got.

#150 Add attribute to allow setting of rsyslog.d configuration directory mode for security compliance
  CHANGELOG.md
  README.md
  attributes/default.rb
  recipes/default.rb
Labels: Release: Minor, Waiting on Contributor

#177 Fixed a bug during auto release
  CHANGELOG.md
Labels: Release: Patch

#174 Enabled custom 35-server-per-host.conf templates
  CHANGELOG.md
  README.md
  attributes/default.rb
  recipes/server.rb
Labels: Release: Minor

#162 Add facility to choose TLS driver
  README.md
  attributes/default.rb
  recipes/default.rb
  recipes/server.rb
  spec/server_spec.rb
  templates/default/rsyslog.conf.erb
Labels: Release: Minor
